var s ='';
s +='	 <footer>';
s +='		<div class="link">';
s +='			<div class="container clearfix">';
s +='				<div class="logo left"><a href="/"><img src="/images/common/img_logo_w.png" alt="株式会社インフォテクノ朝日"></a></div>';
s +='				<ul class="right">';
s +='					<li><a href="/company.html">会社概要</a></li>';
s +='					<li><a href="/business.html">事業について</a></li>';
s +='					<li><a href="/message.html">トップメッセージ</a></li>';
s +='					<li><a href="/recruit/" target="_blank">採用TOP</a></li>';
s +='				</ul>';
s +='			</div>';
s +='		</div>';
s +='		<div class="sub">';
s +='			<div class="container">';
s +='				<div class="wrap">';
s +='					<ul class="">';
s +='						<li><a href="/sitemap.html">サイトマップ</a></li>';
s +='						<li><a href="/privacy.html">個人情報保護方針</a></li>';
s +='					</ul>';
s +='					<div class="box">';
s +='						<p>©2020 Info Techno Asahi All Rights Reserved.</p>';
s +='					</div>';
s +='				</div>';
s +='			</div>';
s +='		</div>';
s +='	</footer>';
s +='<div class="pagetop"><a href="#top"><span></span></a></div>';
document.write(s);
