var s ='';
s +='	<header class="clearfix">';
s +='		<div class="base">';
s +='			<div class="header-menu clearfix">';
s +='				<div class="icon">';
s +='					<img src="/images/common/img_20th_mark.png" alt="20周年" class="ita20">';
s +='					<a href="//www.mhlw.go.jp/stf/seisakunitsuite/bunya/kodomo/shokuba_kosodate/kurumin/index.html" target="_blank"><img src="/images/common/img_kurumin_mark.png" alt="プラチナくるみん" class="kurumin"></a>';
s +='					<a href="/privacy.html"><img src="/images/common/img_p_mark_s.png" alt="たいせつにしますプライバシー" class="privacy"></a>';
s +='				</div>';
s +='				<div class="menu-btn"><span></span></div>';
s +='				<h1><a href="/"><img src="/images/common/img_logo.png" alt="株式会社インフォテクノ朝日"></a></h1>';
s +='			</div>';
s +='		</div>';
s +='		<nav class="nav close clearfix">';
s +='			<ul class="gnav clearfix">';
s +='				<li><a href="/company.html"><span class="en">COMPANY PROFILE</span>会社概要</a></li>';
s +='				<li><a href="/business.html"><span class="en">OUR BUSINESS</span>事業について</a></li>';
s +='				<li><a href="/message.html"><span class="en">TOP MESSAGE</span>トップメッセージ</a></li>';
s +='				<li><a href="/recruit/" target="_blank"><span class="en">RECRUIT</span>採用サイト</a></li>';
s +='				<li><a href="/privacy.html"><span class="en">PRIVACY</span>個人情報保護方針</a></li>';
s +='				<li><a href="/news.html"><span class="en">NEWS</span>おしらせ</a></li>';
s +='				<li><a href="/sitemap.html"><span class="en">SITE MAP</span>サイトマップ</a></li>';
s +='			</ul>';
s +='			<div class="address">';
s +='				<dl>';
s +='					<dt>ADDRESS</dt>';
s +='					<dd>〒206-8611<br>東京都多摩市鶴牧1－23<br>朝日生命多摩本社ビル</dd>';
s +='				</dl>';
s +='				<dl>';
s +='					<dt>TEL</dt>';
s +='					<dd><span class="tel">042-338-3189</span></dd>';
s +='				</dl>';
s +='			</div>';
s +='		</nav>';
s +='	</header>';
document.write(s);
